# Machine Learning Algorithms Testing

In [217]:
import os
import pandas as pd
from os import path
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix


#LR libraries
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

#KNN libraries
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

#RF libraries
# source - https://www.datacamp.com/tutorial/random-forests-classifier-python
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV

#SVM libraries
from sklearn import svm
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

#Ensemble
from mlxtend.classifier import StackingClassifier

In [218]:
path = os.getcwd()
text_features = pd.read_csv(path + "/extracted_TRAD_LEX.csv")
text_features_header = ["Word Count", "Sentence Count", "Ave. Word Length", "Ave. Sentence Length", "Total Syllables", "Noun-Token Ratio",
                        "Verb-Token Ratio", "Type-Token Ratio", "Root TTR", "Corrected TTR", "Bilogarithmic TTR", "Lexical Density",
                        "FW-Token Ratio", "Age Classification"]

text_features

Word Count  Sentence Count  Ave. Word Length  Ave. Sentence Length   
0         973              85          5.216380             13.823529  \
1         937              95          5.048168             12.105263   
2         900              72          4.793478             15.097222   
3        1279              97          4.959199             16.319588   
4         876              75          4.849498             14.053333   
5        1177             137          5.007531             10.883212   
6        1601             120          5.328449             15.816667   
7        1365             132          4.945166             12.393939   
8         975              92          4.995984             12.347826   
9         552              69          4.984211             10.231884   

   Total Syllables  Noun-Token Ratio  Verb-Token Ratio  Type-Token Ratio   
0             2096          0.212914          0.113438          0.009599  \
1             2018          0.171946          0.103167          0.009955   
2             1844          0.136999          0.105312          0.010252   
3             2596          0.192617          0.100000          0.007383   
4             1824          0.195192          0.103846          0.010577   
5             2491          0.178177          0.104972          0.007597   
6             3610          0.175055          0.143326          0.006018   
7             2896          0.191083          0.134395          0.007006   
8             2089          0.145889          0.139699          0.009726   
9             1177          0.129851          0.129851          0.016418   

   Root TTR  Corrected TTR  Bilogarithmic TTR  Lexical Density   
0  0.324938       0.229766           0.340415         0.403141  \
1  0.330911       0.233990           0.342185         0.412670   
2  0.335809       0.237453           0.343626         0.367195   
3  0.284970       0.201504           0.328185         0.405369   
4  0.341096       0.241191           0.345171         0.388462   
5  0.289074       0.204406           0.329475         0.381906   
6  0.257279       0.181924           0.319252         0.407549   
7  0.277615       0.196303           0.325853         0.407643   
8  0.327086       0.231284           0.341053         0.416446   
9  0.424967       0.300497           0.368494         0.374627   

   FW-Token Ratio  Age Classification  
0        0.017452                  10  
1        0.021719                  10  
2        0.033551                   9  
3        0.015436                  12  
4        0.001923                   9  
5        0.016575                  12  
6        0.004376                   9  
7        0.012102                  12  
8        0.002653                  10  
9        0.007463                   9

In [219]:
X = text_features[text_features_header[:-1]].values
y = text_features[['Age Classification']].values.ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Logistic Regression

In [220]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_scaled, y_train)

lr_pred = logreg.predict(X_test_scaled)
print("Predictions: ", lr_pred)

accuracy = accuracy_score(y_test, lr_pred)
conf_matrix = confusion_matrix(y_test, lr_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


### K-Nearest Neighbors

In [221]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train_scaled, y_train)

knn_pred = knn.predict(X_test_scaled)
print("Predictions: ", knn_pred)

accuracy = accuracy_score(y_test, knn_pred)
conf_matrix = confusion_matrix(y_test, knn_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [10 12]
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


### Random Forest

In [222]:
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

rf_pred = rf.predict(X_test_scaled)
print("Predictions: ", rf_pred)

accuracy = accuracy_score(y_test, rf_pred)
conf_matrix = confusion_matrix(y_test, rf_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [10 12]
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


### Support Vector Machine

In [223]:
clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(X_train_scaled, y_train)

svm_pred = clf_svm.predict(X_test_scaled)
print("Predictions: ", svm_pred)

accuracy = accuracy_score(y_test, svm_pred)
conf_matrix = confusion_matrix(y_test, svm_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


## Ensemble Methods

Create meta-model

In [224]:
# used Stacking based on this source: https://www.geeksforgeeks.org/stacking-in-machine-learning-2/
# meta-model used: Linear Regression

meta_model = LogisticRegression()

#### LR + SVM

In [225]:
lr_svm_stack = StackingClassifier(classifiers =[logreg, clf_svm], meta_classifier = meta_model)

model_stack = lr_svm_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + KNN

In [226]:
lr_knn_stack = StackingClassifier(classifiers =[logreg, knn], meta_classifier = meta_model)

model_stack = lr_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + RF

In [227]:
lr_rf_stack = StackingClassifier(classifiers =[logreg, rf], meta_classifier = meta_model)

model_stack = lr_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + KNN

In [228]:
svm_knn_stack = StackingClassifier(classifiers =[clf_svm, knn], meta_classifier = meta_model)

model_stack = svm_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + RF

In [229]:
svm_rf_stack = StackingClassifier(classifiers =[clf_svm, rf], meta_classifier = meta_model)

model_stack = svm_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### KNN + RF

In [ ]:
knn_rf_stack = StackingClassifier(classifiers =[knn, rf], meta_classifier = meta_model)

model_stack = knn_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')