# Machine Learning Algorithms Testing

In [62]:
import os
import pandas as pd
from os import path
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import MultiLabelBinarizer

#LR libraries
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

#KNN libraries
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

#RF libraries
# source - https://www.datacamp.com/tutorial/random-forests-classifier-python
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV

#SVM libraries
from sklearn import svm
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# DT
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

# #Ensemble
# from mlxtend.classifier import StackingClassifier

In [90]:
path = os.getcwd()
text_features = pd.read_csv(path + "/book.csv")
text_features_header = list(text_features.columns)

text_features

Unnamed: 0  Word Count  Sentence Count  AVG Word Length  \
0           0        1177             137         5.084112   
1           1        1365             132         5.021245   
2           2        1279              97         5.036747   
3           3         876              75         4.965753   
4           4         975              92         5.103590   
5           5         552              69         5.146739   
6           6        1601             120         5.451593   
7           7         900              72         4.900000   
8           8         937              95         5.145144   
9           9         973              85         5.302158   

   AVG Sentence Length  Total Syllables  MONOSYLL  POLYSYLL       NTR  \
0             8.591241             2491       379       797  0.178177   
1            10.340909             2896       498       867  0.191083   
2            13.185567             2596       511       766  0.192617   
3            11.680000             1824       276       600  0.195192   
4            10.597826             2089       336       638  0.145889   
5             8.000000             1177       188       363  0.129851   
6            13.341667             3610       604       996  0.175055   
7            12.500000             1844       332       563  0.136999   
8             9.863158             2018       321       615  0.171946   
9            11.447059             2096       299       665  0.212914   

        VTR       TTR  Root TTR  Corrected TTR  BiLog TTR        LD      FWTR  \
0  0.104972  0.007597  0.289074       0.204406   0.329475  0.381906  0.016575   
1  0.134395  0.007006  0.277615       0.196303   0.325853  0.407643  0.012102   
2  0.100000  0.007383  0.284970       0.201504   0.328185  0.405369  0.015436   
3  0.103846  0.010577  0.341096       0.241191   0.345171  0.388462  0.001923   
4  0.139699  0.009726  0.327086       0.231284   0.341053  0.416446  0.002653   
5  0.129851  0.016418  0.424967       0.300497   0.368494  0.374627  0.007463   
6  0.143326  0.006018  0.257279       0.181924   0.319252  0.407549  0.004376   
7  0.105312  0.010252  0.335809       0.237453   0.343626  0.367195  0.033551   
8  0.103167  0.009955  0.330911       0.233990   0.342185  0.412670  0.021719   
9  0.113438  0.009599  0.324938       0.229766   0.340415  0.403141  0.017452   

    AGE  
0  8-16  
1  8-16  
2  8-16  
3  6-12  
4  8-12  
5  6-12  
6  6-12  
7  6-12  
8  8-12  
9  8-12

In [126]:
# # tried multi-binarizing stuff here
# # decisions trees lang gumana,,, other algos don't support it :_(

# data = text_features['AGE'].apply(lambda x: [x]).tolist()
# print(data)
# mlb = MultiLabelBinarizer()

# encoded_data = mlb.fit_transform(data)

# encoded_df = pd.DataFrame(encoded_data, columns=mlb.classes_)

# print(encoded_df)


In [139]:
X = text_features[text_features_header[:-1]].values
y = text_features[['AGE']].values.ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Logistic Regression

In [142]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_scaled, y_train)

lr_pred = logreg.predict(X_test_scaled)
print("Predictions: ", lr_pred)

accuracy = accuracy_score(y_test, lr_pred)
conf_matrix = confusion_matrix(y_test, lr_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['8-12' '8-16']
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


### K-Nearest Neighbors

In [143]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train_scaled, y_train)

knn_pred = knn.predict(X_test_scaled)
print("Predictions: ", knn_pred)

accuracy = accuracy_score(y_test, knn_pred)
conf_matrix = confusion_matrix(y_test, knn_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['8-12' '8-16']
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


/Users/jerseydayao/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


### Random Forest

In [144]:
rf = RandomForestClassifier(n_estimators=100, random_state=7)
rf.fit(X_train_scaled, y_train)

rf_pred = rf.predict(X_test_scaled)
print("Predictions: ", rf_pred)

accuracy = accuracy_score(y_test, rf_pred)
conf_matrix = confusion_matrix(y_test, rf_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['8-12' '8-16']
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


### Support Vector Machine

In [145]:
clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(X_train_scaled, y_train)

svm_pred = clf_svm.predict(X_test_scaled)
print("Predictions: ", svm_pred)

accuracy = accuracy_score(y_test, svm_pred)
conf_matrix = confusion_matrix(y_test, svm_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['8-12' '8-16']
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 1]]


### Decision Trees

In [146]:
clf = DecisionTreeClassifier()

clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


## Ensemble Methods

Create meta-model

In [224]:
# used Stacking based on this source: https://www.geeksforgeeks.org/stacking-in-machine-learning-2/
# meta-model used: Linear Regression

meta_model = LogisticRegression()

#### LR + SVM

In [225]:
lr_svm_stack = StackingClassifier(classifiers =[logreg, clf_svm], meta_classifier = meta_model)

model_stack = lr_svm_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + KNN

In [226]:
lr_knn_stack = StackingClassifier(classifiers =[logreg, knn], meta_classifier = meta_model)

model_stack = lr_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + RF

In [227]:
lr_rf_stack = StackingClassifier(classifiers =[logreg, rf], meta_classifier = meta_model)

model_stack = lr_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + KNN

In [228]:
svm_knn_stack = StackingClassifier(classifiers =[clf_svm, knn], meta_classifier = meta_model)

model_stack = svm_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + RF

In [229]:
svm_rf_stack = StackingClassifier(classifiers =[clf_svm, rf], meta_classifier = meta_model)

model_stack = svm_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### KNN + RF

In [ ]:
knn_rf_stack = StackingClassifier(classifiers =[knn, rf], meta_classifier = meta_model)

model_stack = knn_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')