# Machine Learning Algorithms Testing

In [80]:
import os
import pandas as pd
from os import path
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix


# LR libraries
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# KNN libraries
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

#RF libraries
# source - https://www.datacamp.com/tutorial/random-forests-classifier-python
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV

# SVM libraries
from sklearn import svm
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# DT
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

# #Ensemble
# from mlxtend.classifier import StackingClassifier

In [9]:
path = os.getcwd()
text_features = pd.read_csv(path + "/sentence.csv")
text_features_header = ['Title', 'Word Count', 'AVG Word Length', 'Total Syllables', 'MONOSYLL', 'POLYSYLL', 'NTR', 'VTR', 
                        'TTR', 'Root TTR', 'Corrected TTR', 'BiLog TTR', 'LD', 'FWTR', 'Age Classification']

text_features

Title  Word Count  AVG Word Length  Total Syllables  MONOSYLL  POLYSYLL  \
0       0          10         5.100000               21         4         6   
1       1          15         5.066667               34         4        11   
2       2           6         4.333333               11         2         4   
3       3          12         5.250000               27         4         8   
4       4           8         5.500000               19         3         5   
..    ...         ...              ...              ...       ...       ...   
95     95           6         5.166667               13         2         4   
96     96           8         4.375000               16         4         4   
97     97          15         4.800000               33         5        10   
98     98           2         4.000000                4         0         2   
99     99           4         6.000000               10         0         4   

         NTR       VTR       TTR  Root TTR  Corrected TTR  BiLog TTR  \
0   0.200000  0.100000  0.600000  1.897367       1.341641   0.778151   
1   0.266667  0.066667  0.400000  1.549193       1.095445   0.661642   
2   0.333333  0.000000  0.666667  1.632993       1.154701   0.773706   
3   0.250000  0.166667  0.500000  1.732051       1.224745   0.721057   
4   0.125000  0.250000  0.750000  2.121320       1.500000   0.861654   
..       ...       ...       ...       ...            ...        ...   
95  0.000000  0.333333  0.666667  1.632993       1.154701   0.773706   
96  0.125000  0.250000  0.625000  1.767767       1.250000   0.773976   
97  0.133333  0.133333  0.333333  1.290994       0.912871   0.594316   
98  0.500000  0.000000  1.000000  1.414214       1.000000   1.000000   
99  0.000000  0.250000  1.000000  2.000000       1.414214   1.000000   

          LD  FWTR Age Classification  
0   0.400000   0.0               8-12  
1   0.400000   0.0               8-12  
2   0.500000   0.0               8-12  
3   0.583333   0.0               8-12  
4   0.625000   0.0               8-12  
..       ...   ...                ...  
95  0.333333   0.0               6-12  
96  0.625000   0.0               6-12  
97  0.266667   0.0               6-12  
98  0.500000   0.0               6-12  
99  0.750000   0.0               6-12  

[100 rows x 15 columns]

In [70]:
X = text_features[text_features_header[:-1]].values
y = text_features[['Age Classification']].values.ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Logistic Regression

In [74]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_scaled, y_train)

titles_test_samples = text_features.loc[X_test[:, 0], 'Title']

lr_pred = logreg.predict(X_test_scaled)
print("Predictions: ", lr_pred)
# print("Titles of test samples:")
# for title in titles_test_samples:
#     print(title)

accuracy = accuracy_score(y_test, lr_pred)
conf_matrix = confusion_matrix(y_test, lr_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['6-12' '8-16' '6-12' '8-12' '6-12' '6-12' '8-16' '8-16' '8-12' '6-12'
 '6-12' '8-12' '8-16' '6-12' '6-12' '8-12' '8-16' '6-12' '8-16' '8-12'
 '8-16' '6-12' '8-12' '6-12' '8-12' '8-12' '8-16' '8-12' '8-12' '8-12']
Accuracy: 0.5
Confusion Matrix:
[[7 4 3]
 [1 5 2]
 [3 2 3]]


### K-Nearest Neighbors

In [75]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train_scaled, y_train)

knn_pred = knn.predict(X_test_scaled)
print("Predictions: ", knn_pred)

accuracy = accuracy_score(y_test, knn_pred)
conf_matrix = confusion_matrix(y_test, knn_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['6-12' '8-16' '6-12' '8-12' '6-12' '8-12' '8-16' '8-12' '6-12' '6-12'
 '8-12' '8-16' '6-12' '6-12' '8-16' '8-16' '8-16' '6-12' '6-12' '8-12'
 '8-16' '8-12' '6-12' '8-12' '8-12' '6-12' '8-16' '6-12' '6-12' '8-12']
Accuracy: 0.5666666666666667
Confusion Matrix:
[[8 2 4]
 [1 6 1]
 [4 1 3]]


/Users/jerseydayao/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


### Random Forest

In [76]:
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

rf_pred = rf.predict(X_test_scaled)
print("Predictions: ", rf_pred)

accuracy = accuracy_score(y_test, rf_pred)
conf_matrix = confusion_matrix(y_test, rf_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['6-12' '6-12' '8-16' '8-12' '6-12' '8-12' '8-16' '8-12' '8-12' '8-16'
 '6-12' '6-12' '6-12' '8-16' '8-16' '8-16' '8-16' '6-12' '6-12' '8-12'
 '8-12' '6-12' '6-12' '6-12' '8-12' '6-12' '8-16' '6-12' '8-16' '8-12']
Accuracy: 0.6333333333333333
Confusion Matrix:
[[8 1 5]
 [1 7 0]
 [4 0 4]]


### Support Vector Machine

In [77]:
clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(X_train_scaled, y_train)

svm_pred = clf_svm.predict(X_test_scaled)
print("Predictions: ", svm_pred)

accuracy = accuracy_score(y_test, svm_pred)
conf_matrix = confusion_matrix(y_test, svm_pred)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  ['6-12' '8-16' '6-12' '8-12' '6-12' '6-12' '8-16' '6-12' '8-12' '6-12'
 '6-12' '6-12' '6-12' '6-12' '6-12' '8-12' '8-16' '6-12' '8-16' '8-12'
 '8-16' '6-12' '8-12' '6-12' '8-12' '8-12' '8-16' '8-12' '6-12' '8-12']
Accuracy: 0.6
Confusion Matrix:
[[10  2  2]
 [ 2  5  1]
 [ 3  2  3]]


## Decision Trees

In [79]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.7333333333333333


## Ensemble Methods

Create meta-model

In [ ]:
# used Stacking based on this source: https://www.geeksforgeeks.org/stacking-in-machine-learning-2/
# meta-model used: Linear Regression

meta_model = LogisticRegression()

#### LR + SVM

In [ ]:
lr_svm_stack = StackingClassifier(classifiers =[logreg, clf_svm], meta_classifier = meta_model)

model_stack = lr_svm_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + KNN

In [ ]:
lr_knn_stack = StackingClassifier(classifiers =[logreg, knn], meta_classifier = meta_model)

model_stack = lr_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### LR + RF

In [ ]:
lr_rf_stack = StackingClassifier(classifiers =[logreg, rf], meta_classifier = meta_model)

model_stack = lr_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + KNN

In [ ]:
svm_knn_stack = StackingClassifier(classifiers =[clf_svm, knn], meta_classifier = meta_model)

model_stack = svm_knn_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### SVM + RF

In [ ]:
svm_rf_stack = StackingClassifier(classifiers =[clf_svm, rf], meta_classifier = meta_model)

model_stack = svm_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')

Predictions:  [ 9 12]
Accuracy: 0.5
Confusion Matrix:
[[0 0 0]
 [1 0 0]
 [0 0 1]]


#### KNN + RF

In [ ]:
knn_rf_stack = StackingClassifier(classifiers =[knn, rf], meta_classifier = meta_model)

model_stack = knn_rf_stack.fit(X_train_scaled, y_train)
pred_stack = model_stack.predict(X_test_scaled)
print("Predictions: ", pred_stack)

accuracy = accuracy_score(y_test, pred_stack)
conf_matrix = confusion_matrix(y_test, pred_stack)
print("Accuracy:", accuracy)
print(f'Confusion Matrix:\n{conf_matrix}')